# Main.py
from PyQt5 import QtWidgets, uic
import fileset as fs
import datetime
import json
import sys


class UiDataCreatorWindow(QtWidgets.QDialog):
    """"
        GUI for creation of various datasets, either manual or automated.
        DataCreatorWindow.ui is generated by QtDesigner version 6.4.1
    """
    def __init__(self):
        super(UiDataCreatorWindow, self).__init__()

        # Load the UI,
        # Note that loadUI adds objects to 'self' using objectName
        uic.loadUi("DataCreatorWindow.ui", self)

        self.fileset = fs.Fileset(datetime.datetime.now().strftime("%d_%m_%Y"))

        # Set starting tab to manual data creation
        self.tabWidget.setCurrentIndex(0)

        # Define widget action
        self.browseFilesBtn.clicked.connect(self.browse_files)
        self.browseDirBtn.clicked.connect(self.browse_dir)
        self.addLabelBtn.clicked.connect(self.add_file_to_set)
        self.generateBtn.clicked.connect(self.generate_set)
        self.resetBtn.clicked.connect(self.reset)
        self.doneBtn.clicked.connect(self.finish)

        # Enable button when all is filled
        self.showSetPlainText.textChanged.connect(self.button_state)
        self.nameEdit.textChanged.connect(self.button_state)

        # Show the app
        self.show()

    def browse_files(self):
        # Open file selection file dialog and update GUI
        file_name = QtWidgets.QFileDialog.getOpenFileName(self, "Open File")
        self.browseFilesText.setPlainText(file_name[0])

    def browse_dir(self):
        # Open directory selection file dialog and update GUI
        dir_name = QtWidgets.QFileDialog.getExistingDirectory(self, 'Select Directory')
        self.browseDirText.setPlainText(dir_name)

    def add_file_to_set(self):
        # Read name and legend label from GUI
        file_name = self.browseFilesText.toPlainText()
        file_label = self.labelEdit.text()

        # Check for duplicate label
        if file_label in self.fileset.get_labels():
            msg = QtWidgets.QMessageBox()
            msg.setWindowTitle("Duplicate Label")
            msg.setText("""This label has already been used. Choose another label and try again.""")
            msg.exec_()
        else:
            # Add the file to the dataset and update the GUI
            self.fileset.add_filepath(file_name, file_label)
            self.showSetPlainText.setPlainText(
                json.dumps(
                    self.fileset.get_filepaths(),
                    indent=4,
                    separators=(',', ': ')
                )
            )
            self.browseFilesText.clear()

        # Empty label widget
        self.labelEdit.clear()

    def generate_set(self):
        try:
            path = self.browseDirText.toPlainText()
            errors = self.fileset.construct_structured_filepaths(path)

            # Show the directories/files that were ignored to the user
            if errors != "":
                msg = QtWidgets.QMessageBox()
                msg.setWindowTitle("Files were ignored")
                msg.setText(errors)
                x = msg.exec_()

            # Show the files in the GUI
            self.showSetPlainText.setPlainText(
                json.dumps(
                    self.fileset.get_filepaths(),
                    indent=4,
                    separators=(',', ': ')
                )
            )

        except Exception as e:
            self.console_print(f"Fatal Err: Plot aborted{e}")

    def button_state(self):
        # The GUI should not be closed while the dataset is still empty
        nameTxt = self.nameEdit.text()
        files = self.showSetPlainText.toPlainText()
        if (files != "") and (nameTxt != ""):
            self.doneBtn.setEnabled(True)
        else:
            self.doneBtn.setEnabled(False)

    def reset(self):
        self.nameEdit.clear()
        self.labelEdit.clear()
        self.browseDirText.clear()
        self.browseFilesText.clear()
        self.showSetPlainText.clear()
        self.button_state()

    def finish(self):
        # Add name, data and device type to the dataset before exiting
        self.fileset.set_name(self.nameEdit.text())
        self.fileset.set_device(self.dataTypeCombo.currentText())
        self.done(1)


if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    window = UiDataCreatorWindow()
    app.exec_()
