# Main.py
from PyQt5 import QtWidgets, uic
import datetime
import natsort
import json
import sys
import os


class UiDataCreatorWindow(QtWidgets.QDialog):
    """"
        GUI for creation of various datasets, either manual or automated.
        DataCreatorWindow.ui is generated by QtDesigner version 6.4.1
    """
    def __init__(self):
        super(UiDataCreatorWindow, self).__init__()

        # Load the UI,
        # Note that loadUI adds objects to 'self' using objectName
        uic.loadUi("DataCreatorWindow.ui", self)

        # Create empty dataset
        self.data = {
            'name': '',
            'date': '',
            'device': '',
            'autogen': False,
            'notes': '',
            'console': {},
            'files': {}
        }

        # Set starting tab to manual data creation
        self.tabWidget.setCurrentIndex(0)

        # Define widget action
        self.browseFilesBtn.clicked.connect(self.browse_files)
        self.browseDirBtn.clicked.connect(self.browse_dir)
        self.addLabelBtn.clicked.connect(self.add_file_to_set)
        self.generateBtn.clicked.connect(self.generate_set)
        self.resetBtn.clicked.connect(self.reset)
        self.doneBtn.clicked.connect(self.finish)

        # Enable button when all is filled
        self.showSetPlainText.textChanged.connect(self.button_state)
        self.nameEdit.textChanged.connect(self.button_state)

        # Show the app
        self.show()

    def browse_files(self):
        # Open file selection file dialog and update GUI
        file_name = QtWidgets.QFileDialog.getOpenFileName(self, "Open File")
        self.browseFilesText.setPlainText(file_name[0])

    def browse_dir(self):
        # Open directory selection file dialog and update GUI
        dir_name = QtWidgets.QFileDialog.getExistingDirectory(self, 'Select Directory')
        self.browseDirText.setPlainText(dir_name)

    def add_file_to_set(self):
        # Read name and legend label from GUI
        file_name = self.browseFilesText.toPlainText()
        file_label = self.labelEdit.text()

        # Check for duplicate label
        if file_label in self.data['files'].keys():
            msg = QtWidgets.QMessageBox()
            msg.setWindowTitle("Duplicate Label")
            msg.setText("""This label has already been used. Choose another label and try again.""")
            x = msg.exec_()
        else:
            # Add the file to the dataset and update the GUI
            self.data['files'][file_label] = file_name
            self.showSetPlainText.setPlainText(
                json.dumps(
                    self.data['files'],
                    indent=4,
                    separators=(',', ': ')
                )
            )
            self.browseFilesText.clear()

        # Empty label widget
        self.labelEdit.clear()

        # Set auto generation flag to False
        self.data['autogen'] = False

    def generate_set(self):
        try:
            path = self.browseDirText.toPlainText()
            subdirs = natsort.natsorted(os.listdir(path))

            # Automated dataset creation is only allowed to go into subdirectories once
            # If items in subdirectories are not files then they will be ignored
            errors = ""
            for dir in subdirs:
                # If the item in the parent directory is a file add it directly
                dirpath = f"{path}/{dir}"
                if os.path.isfile(dirpath):
                    self.data['files'][dir] = dirpath
                    print(f"File added {dirpath}")
                else:
                    # Create nested dict for directory and check all items within
                    self.data['files'][dir] = {}
                    for file in os.listdir(dirpath):
                        # Only append to dataset if the item is actually a file
                        filepath = f"{path}/{dir}/{file}"
                        if os.path.isfile(filepath):
                            self.data['files'][dir][file] = filepath
                        # Ignore otherwise
                        else:
                            errors += f"Ignored {dir}/{file} as it is not a file\n"
                            print("Item ignored")

            # Show the directories/files that were ignored to the user
            if errors != "":
                msg = QtWidgets.QMessageBox()
                msg.setWindowTitle("Files were ignored")
                msg.setText(errors)
                x = msg.exec_()

            # Show the files in the GUI
            self.showSetPlainText.setPlainText(
                json.dumps(
                    self.data['files'],
                    indent=4,
                    separators=(',', ': ')
                )
            )
            # Set autogeneration flag
            self.data['autogen'] = True
        except Exception as e:
            self.console_print(f"Fatal Err: Plot aborted{e}")

    def button_state(self):
        # The GUI should not be closed while the dataset is still empty
        nameTxt = self.nameEdit.text()
        files = self.showSetPlainText.toPlainText()
        if (files != "") and (nameTxt != ""):
            self.doneBtn.setEnabled(True)
        else:
            self.doneBtn.setEnabled(False)

    def reset(self):
        self.nameEdit.clear()
        self.labelEdit.clear()
        self.browseDirText.clear()
        self.browseFilesText.clear()
        self.showSetPlainText.clear()
        self.button_state()

    def finish(self):
        # Add name, data and device type to the dataset before exiting
        self.data['name'] = self.nameEdit.text()
        self.data['date'] = datetime.datetime.now().strftime("%d_%m_%Y")
        self.data['device'] = self.dataTypeCombo.currentText()
        self.done(1)


if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    window = UiDataCreatorWindow()
    app.exec_()
