# Main.py
from PyQt5 import QtWidgets, uic
import datetime
import json
import sys
import Devices as Dev
import DataCreatorWindow


class UiMainWindow(QtWidgets.QMainWindow):
    """
        GUI for automated plotting of various types of data.
        MainWindow.ui is generated by QtDesigner version 6.4.1
    """
    def __init__(self):
        super(UiMainWindow, self).__init__()

        # Create empty dataset and copy it to the current dataset
        self.init_data = {
            'name': '',
            'date': '',
            'device': '',
            'autogen': False,
            'notes': '',
            'console': {},
            'files': {}
        }
        self.data = self.init_data.copy()

        # Define device indices corresponding to stackedWidget definition (see QtDesigner)
        self.devices = {
            '': 0,
            'Sunbrick': 1,
            'DW2000': 2,
            'LBIC': 3,
            'PDS': 4,
            'PTI': 5,
            'Generic': 6
        }

        # Define possible plot types to show to the user for each device
        self.plot_types = {
            'Sunbrick': ['plot_iv', 'plot_fulliv', 'plot_pv', 'plot_stability', 'print'],
            'DW2000': ['plot', 'plot_rainbow'],
            'LBIC': ['show_image', 'show_3d', 'plot_intensities', 'plot_horiz_profile'],
            'PDS': ['plot'],
            'PTI': ['plot'],
            'Generic': ['plot', 'plot_distribution']
        }

        # Load the UI,
        # Note that loadUI adds objects to 'self' using objectName
        self.dataWindow = None
        uic.loadUi("MainWindow.ui", self)

        # Reset stacked widget to empty page
        self.stackedWidget.setCurrentWidget(self.stackedWidget.widget(0))

        # Define widget action
        self.actionQuit.triggered.connect(self.quit)

        self.actionCreate.triggered.connect(self.create_data)
        self.actionSave.triggered.connect(self.save_data)
        self.actionLoad.triggered.connect(self.open_data_file)

        self.actionAbout.triggered.connect(self.show_about)

        self.showDataBtn.clicked.connect(self.display_data)
        self.showHistoryBtn.clicked.connect(self.display_history)
        self.addNotesBtn.clicked.connect(self.add_notes)

        self.appendBtn.clicked.connect(self.append_console_to_set)
        self.clearBtn.clicked.connect(self.clear_data)
        self.clearAllBtn.clicked.connect(self.clear_all)
        self.quitBtn.clicked.connect(self.quit)

        # Define stackedWidget widget actions
        self.lbicProfilesCheckBox.stateChanged.connect(self.toggle_lbic_profile)
        self.plotBtn.clicked.connect(self.plot_manager)

        # Show the app
        self.show()

    def create_data(self):
        # Run the DataCreatorWindow
        self.dataWindow = DataCreatorWindow.UiDataCreatorWindow()
        self.dataWindow.show()

        if self.dataWindow.exec() == 1:
            # If the window was properly closed (Done button) then creation was successful
            #     Copy data and print to console
            self.clear_data()
            self.data = self.dataWindow.data.copy()
            self.console_print(f"Dataset created")
            self.console_print("Warning: Dataset must be saved")
            self.load_data()
            self.update_header()
        else:
            # Warn user that window was improperly closed and that no data was created
            self.console_print("No data was created")

    def save_data(self):
        # Make sure there is data to save
        if not self.data:
            self.console_print("Err: Must first load data")
            return 1

        # Run the file dialog
        file_name = QtWidgets.QFileDialog.getSaveFileName(self, "Save file to disk")[0]
        if file_name != "":
            # Dump the data into a json file
            with open(file_name, "w") as json_file:
                json.dump(self.data, json_file)
            json_file.close()
            self.console_print(f"Saved data to {file_name}")
        else:
            # File dialog was exited without choosing a file
            self.console_print(f"No file selected")

    def open_data_file(self):
        # Reset
        self.clear_data()
        self.consolePlainText.clear()

        # Choose file
        file_name = QtWidgets.QFileDialog.getOpenFileName(self, "Open Files")[0]
        if file_name != '':
            # Open then load the json file and update GUI
            with open(file_name) as json_file:
                self.data = json.load(json_file)
                self.console_print(f"Opened {file_name}")
            self.notesPlainText.setPlainText(self.data['notes'])
            self.load_data()
            self.update_header()
        else:
            # File not chosen
            self.console_print(f"Err: No file loaded")

    def load_data(self):
        # Add all top level keys to the selection list of the GUI
        for file in self.data['files']:
            self.selectedFilesList.addItem(file)

        # For lbic plot type set selection to first item, otherwise preselect all items
        if self.data['device'] == "LBIC":
            self.selectedFilesList.setCurrentRow(0)
        else:
            self.selectedFilesList.selectAll()

        # Edit combobox to show all available plot types
        for plot_type in self.plot_types[self.data['device']]:
            self.plotTypeCombo.addItem(plot_type)
        self.console_print("Dataset opened")

    def display_data(self):
        # TODO: This should probably be changed from QMessagebox to something else
        #     The width is insufficient and it needs a scrollbar
        # Abort if no data was loaded
        if not self.data:
            self.console_print("Err: Must first load data")
            return 1
        # Pretty print the data in a simple dialog
        pretty_json = json.dumps(
            self.data,
            indent=4,
            separators=(',', ': ')
        )
        msg = QtWidgets.QMessageBox()
        msg.setWindowTitle(f"Dataset: {self.data['name']}")
        msg.setText(pretty_json)
        msg.exec_()

    def display_history(self):
        # TODO: This should probably be changed from QMessagebox to something else
        #     The width is insufficient and it needs a scrollbar
        if not self.data:
            self.console_print("Err: Must first load data")
            return 1

        # Prints only the console history to a simple dialog
        pretty_history = ""
        for k, v in sorted(self.data['console'].items()):
            line = f"{v}\n"
            pretty_history += line
        msg = QtWidgets.QMessageBox()
        msg.setWindowTitle(f"Dataset: {self.data['name']}")
        msg.setText(pretty_history)
        msg.exec_()

    def add_notes(self):
        # Add any notes to the dataset
        self.data['notes'] = self.notesPlainText.toPlainText()
        self.console_print("Notes added to dataset")
        self.console_print("Warning: Changes must be saved")

    def update_header(self):
        # Header should reflect opened data
        self.currSetNameLineEdit.setText(self.data['name'])
        self.currDeviceLineEdit.setText(self.data['device'])
        self.update_stacked_widget()

    def update_stacked_widget(self):
        # Stacked widget should show the correct widget for the opened data
        new_page = self.stackedWidget.widget(self.devices[self.data['device']])
        self.stackedWidget.setCurrentWidget(new_page)

    def plot_manager(self):
        # Manage plotting
        self.console_print(f"Producing plot for {self.data['name']}")
        # Grab the selected files for plotting
        selected_files = {}
        for item in self.selectedFilesList.selectedItems():
            lbl = item.text()
            selected_files[lbl] = self.data['files'][lbl]

        # Try plotting the data using the proper device (delegate to dedicated plotting function)
        device = self.data['device']
        plot_type = self.plotTypeCombo.currentText()
        try:
            if device == "Sunbrick":
                return_str = self.plot_sunbrick(plot_type, selected_files)
            elif device == "DW2000":
                return_str = self.plot_dw2000(plot_type, selected_files)
            elif device == "LBIC":
                return_str = self.plot_lbic(plot_type, selected_files)
            elif device == "PDS":
                return_str = self.plot_pds(plot_type, selected_files)
            elif device == "PTI":
                return_str = self.plot_pti(plot_type, selected_files)
            elif device == "Generic":
                return_str = self.plot_generic(plot_type, selected_files)
            else:
                return_str = "Err: Unknown device type"

            self.console_print(return_str)
        except Exception as e:
            self.console_print(f"Fatal Err: Plot aborted: {e}")

    def plot_sunbrick(self, plot_type, selected_files):
        # Initialise sunbrick with files and grab relevant parameters
        device = Dev.Sunbrick(selected_files)
        p = self.presentationCheckBox.isChecked()

        # Call the corresponding plot function with the needed parameters
        if plot_type == "plot_iv":
            return device.plot_iv(title=self.data['name'], presentation=p)
        elif plot_type == "plot_fulliv":
            return device.plot_fulliv(title=self.data['name'])
        elif plot_type == "plot_pv":
            return device.plot_pv(title=self.data['name'])
        elif plot_type == 'plot_stability':
            return device.plot_stability(title=self.data['name'])
        elif plot_type == 'print':
            return device.print()
        else:
            return "Unknown plot type, skipped action."

    def plot_dw2000(self, plot_type, selected_files):
        # Initialise DW2000 with a title
        device = Dev.DW2000(self.data['name'])

        # Call the corresponding plot function
        if plot_type == "plot":
            return device.plot(selected_files)
        elif plot_type == "plot_rainbow":
            return device.plot_rainbow(selected_files)
        else:
            return "Unknown plot type, skipped action."

    def toggle_lbic_profile(self):
        # Allow the profile position to be selected (LBIC specific)
        if self.lbicProfilesCheckBox.isChecked():
            self.lbicProfilesSpinBox.setEnabled(True)
        else:
            self.lbicProfilesSpinBox.setDisabled(True)

    def plot_lbic(self, plot_type, selected_files):
        if len(selected_files) != 1:
            # TODO: batch production should be possible now using the label as a title
            return "LBIC only produces one image at a time"

        # Initialise LBIC with a title
        device = Dev.LBIC(self.data['name'])
        profiles = self.lbicProfilesCheckBox.isChecked()

        # Call the corresponding plot function with the needed parameters
        if plot_type == "show_image" or plot_type == "show_3d":
            # Intensity range is required for this type of plot
            intensities = [
                self.intRangeLowSpinBox.value() * 10**(-6),
                self.intRangeUpSpinBox.value() * 10**(-6)
            ]
            self.console_print(f"Range set to {intensities} A")

            if plot_type == "show_image":
                return device.show_image(selected_files, range=intensities, profiles=profiles)
            else:
                return device.show_3d(selected_files, range=intensities)

        elif plot_type == "plot_intensities":
            return device.plot_intensities(selected_files)

        elif plot_type == "plot_horiz_profile":
            # Only plot if profiles were enabled in the GUI
            if profiles:
                ycoord = self.lbicProfilesSpinBox.value()
                return device.plot_horiz_profile(selected_files, ycoord)
            else:
                return "Must enable profile for this plot"
        else:
            return "Unknown plot type, skipped action."

    def plot_pds(self, plot_type, selected_files):
        # Initialise PDS with a title and grab parameters
        device = Dev.PDS(self.data['name'])
        n = self.pdsNormCheckBox.isChecked()
        p = self.presentationCheckBox.isChecked()

        # Call the corresponding plot function with the needed parameters
        if plot_type == "plot":
            return device.plot(selected_files, normalised=n, presentation=p)
        else:
            return "Unknown plot type, skipped action."

    def plot_pti(self, plot_type, selected_files):
        # Initialise PDS with a title
        device = Dev.PtiText(self.data['name'])

        # Call the corresponding plot function
        if plot_type == "plot":
            return device.plot(selected_files)
        else:
            return "Unknown plot type, skipped action."

    def plot_generic(self, plot_type, selected_files):
        x_title = self.xTitleLineEdit.text()
        y_title = self.yTitleLineEdit.text()
        l_title = self.lTitleLineEdit.text()
        device = Dev.Generic(
            title=self.data['name'],
            x_title=x_title,
            y_title=y_title,
            l_title=l_title
        )

        n = self.genericNormCheckBox.isChecked()
        p = self.presentationCheckBox.isChecked()
        if plot_type == "plot":
            return device.plot(selected_files, presentation=p)
        elif plot_type == "plot_distribution":
            return device.plot_distribution(selected_files, presentation=p)
        else:
            return "Unknown plot type, skipped action."

    def console_print(self, fstring):
        # Print a message to the GUI console
        now = datetime.datetime.now()
        self.consolePlainText.appendPlainText(now.strftime("%d/%m/%Y %H.%M.%S: ") + fstring)

    def append_console_to_set(self):
        # Append console contents to the dataset
        console_text = self.consolePlainText.toPlainText()
        now = datetime.datetime.now()
        self.data['console'][now.strftime("%d%m%Y_%H%M%S")] = console_text
        self.console_print("Added console contents to set")

    def clear_data(self):
        # Reset fields and properties related to data
        self.data = self.init_data.copy()

        self.currSetNameLineEdit.clear()
        self.currDeviceLineEdit.clear()
        self.notesPlainText.clear()
        self.console_print("Cleared data from memory")

        self.stackedWidget.setCurrentWidget(self.stackedWidget.widget(0))
        self.selectedFilesList.clear()
        self.plotTypeCombo.clear()

    def clear_all(self):
        # Reset complete GUI
        self.clear_data()
        self.consolePlainText.clear()
        self.console_print("Cleared memory")

    def show_about(self):
        # Grab the "about" info from about.txt
        with open("about.txt") as about_file:
            about_contents = about_file.read()

        # Show a basic about message
        msg = QtWidgets.QMessageBox(self.centralwidget)
        msg.setWindowTitle("About")
        msg.setText(about_contents)
        msg.exec_()

    @staticmethod
    def quit():
        # Terminate the application
        sys.exit()


if __name__ == "__main__":
    # Initialise app, window and start execution
    app = QtWidgets.QApplication(sys.argv)
    window = UiMainWindow()
    app.exec_()
