# Main.py
import os

from PyQt5 import QtWidgets, uic, QtCore
import datetime
import json
import logging
import sys
import fileset as fs
import DataCreatorWindow
from utils.get_class_methods import get_class_methods
from utils.console_colours import ConsoleColours
from utils.logging import with_logging
from utils.get_qwidget_value import get_qwidget_value

# Read the JSON file
with open('config.json') as f:
    config = json.load(f)

# Get the module path
analysis_path = config['analysis_path']

# Add the module path to the system path
sys.path.insert(0, analysis_path)
sys.path.append("..")
# from analysis import device
import analysis
from analysis.device import *

# gui FEATURE REQUEST: ESC should close the window safely
class UiMainWindow(QtWidgets.QMainWindow):
    """
        gui for automated plotting of various types of data.
        MainWindow.ui is generated by QtDesigner version 6.4.1
    """
    def __init__(self):
        super(UiMainWindow, self).__init__()
        self.thread = None
        self.experiment_worker = None
        self.fileset = None
        self.fileset_location = None

        # Load the UI, Note that loadUI adds objects to 'self' using objectName
        self.dataWindow = None
        uic.loadUi("MainWindow.ui", self)

        # Create a logger with the desired settings
        self.logger = logging.getLogger("my_logger")
        self.consoleTextEdit.setFormatter(
            logging.Formatter(
                "%(asctime)s [%(levelname)8.8s] %(message)s",
                datefmt='%d/%m/%Y %H.%M.%S: '
            )
        )
        self.logger.addHandler(self.consoleTextEdit)
        self.logger.setLevel(logging.DEBUG)

        # FEATURE REQUEST: Perhaps pass this logger to an external thing?
        # Decorate methods with the with_logging decorator
        self.load_data = with_logging(self.load_data, self.logger)

        # Grab widgets and corresponding plot types from the analysis package
        self.plot_types = {}
        self.devices = {}
        for entry in analysis.device.__all__:
            entry_ui_file = entry.lower() + ".ui"
            entry_widget = uic.loadUi(config["widgets_path"] + entry_ui_file)
            entry_index = self.stackedWidget.addWidget(entry_widget)
            self.devices[entry] = entry_index

            entry_cls = getattr(analysis.device, entry)
            self.plot_types[entry] = get_class_methods(entry_cls, ignore=["run"])

        # Reset stacked widget to empty page
        self.stackedWidget.setCurrentWidget(self.stackedWidget.widget(0))

        # Define menubar actions
        self.actionCreate_Set.triggered.connect(self.create_data)
        self.actionSave_Set.triggered.connect(self.save_data)
        self.actionLoad_Set.triggered.connect(self.open_data_file)
        self.actionQuit.triggered.connect(self.quit)

        self.actionSave_format.triggered.connect(self.not_implemented)
        self.actionColour_scheme.triggered.connect(self.not_implemented)
        self.actionLine_width.triggered.connect(self.not_implemented)

        self.actionDocumentation.triggered.connect(self.not_implemented)
        self.actionAbout.triggered.connect(self.show_about)

        # Define gui button actions
        self.showDataBtn.clicked.connect(self.display_data)
        self.showHistoryBtn.clicked.connect(self.display_history)
        self.addNotesBtn.clicked.connect(self.add_notes)

        self.appendBtn.clicked.connect(self.append_console_to_set)
        self.clearBtn.clicked.connect(self.clear_data)
        self.clearAllBtn.clicked.connect(self.clear_all)
        self.quitBtn.clicked.connect(self.quit)

        # Define stackedWidget widget actions
        self.lbicProfilesCheckBox.stateChanged.connect(self.toggle_lbic_profile)
        self.plotBtn.clicked.connect(self.plot_manager)

        # Make sure the progress bar is cleared
        self.progressBar.setValue(0)

        # Show the app
        self.show()

    def create_data(self):
        # Run the DataCreatorWindow
        self.dataWindow = DataCreatorWindow.UiDataCreatorWindow()
        self.dataWindow.show()

        if self.dataWindow.exec() == 1:
            # If the window was properly closed (Done button) then creation was successful
            #     Copy data and print to console
            self.clear_data()
            self.fileset = self.dataWindow.fileset
            self.console_print(f"ExperimentDB created")
            self.load_data()
            self.update_header()
            self.save_data()
        else:
            # Warn user that window was improperly closed and that no data was created
            self.console_print("No data was created")

    def autosave(self):
        file_name = self.fileset_location
        if file_name is None:
            return self.console_print("Cannot autosave, no file location known. Open or create dataset first")

        with open(file_name, "w") as json_file:
            json.dump(self.fileset, json_file, cls=fs.FilesetJSONEncoder)
        json_file.close()
        return self.console_print(f"Saved data to {file_name}")

    def save_data(self):
        # Make sure there is data to save
        if self.fileset is None:
            return self.console_print("Err: Must first load data", level="warning")

        # Run the file dialog
        file_name = QtWidgets.QFileDialog.getSaveFileName(self, "Save file to disk")[0]
        if file_name != "":
            # Dump the data into a json file and remember the location
            self.fileset_location = file_name
            with open(file_name, "w") as json_file:
                json.dump(self.fileset, json_file, cls=fs.FilesetJSONEncoder)
            json_file.close()

            return self.console_print(f"Saved data to {file_name}")
        else:
            # File dialog was exited without choosing a file
            return self.console_print(f"No file selected")

    def open_data_file(self):

        # Choose file
        file_name = QtWidgets.QFileDialog.getOpenFileName(self, "Open Files")[0]
        if file_name != '':
            # Reset data
            self.clear_data()
            self.consoleTextEdit.clear()

            # Open then load the json file, remember the location and update gui
            self.fileset_location = file_name
            with open(file_name) as json_file:
                self.fileset = json.load(json_file, cls=fs.FilesetJSONDecoder)
                self.console_print(f"Opened {file_name}")
            self.notesPlainText.setPlainText(self.fileset.get_notes())
            self.load_data()
            self.update_header()
        else:
            # File not chosen
            self.console_print(f"Err: No file loaded", level="warning")

    def load_data(self):
        # Add all top level keys to the selection list of the gui
        for label in self.fileset.get_labels():
            self.selectedFilesList.addItem(label)

        # Some changes depend on the type of device
        current_device = self.fileset.get_device()

        # For lbic plot type set selection to first item, otherwise preselect all items
        if current_device == "LBIC":
            self.selectedFilesList.setCurrentRow(0)
        else:
            self.selectedFilesList.selectAll()

        # Edit combobox to show all available plot types
        for plot_type in self.plot_types[current_device]:
            self.plotTypeCombo.addItem(plot_type)

        self.console_print("ExperimentDB loaded")

    def display_data(self):
        # gui FEATURE REQUEST: This should probably be changed from QMessagebox to something else
        #     The width is insufficient and it needs a scrollbar
        # Abort if no data was loaded
        if self.fileset is None:
            return self.console_print("Err: Must first load data", level="warning")

        # Pretty print the data in a simple dialog
        pretty_json = json.dumps(
            self.fileset,
            indent=4,
            separators=(',', ': '),
            cls=fs.FilesetJSONEncoder
        )
        msg = QtWidgets.QMessageBox()
        msg.setWindowTitle(f"ExperimentDB: {self.fileset.get_name()}")
        msg.setText(pretty_json)
        msg.exec_()

    def display_history(self):
        # gui FEATURE REQUEST: This should probably be changed from QMessagebox to something else
        #     The width is insufficient and it needs a scrollbar
        if self.fileset is None:
            return self.console_print("Err: Must first load data", level="warning")

        # Prints only the console history to a simple dialog
        pretty_history = ""
        for k, v in sorted(self.fileset.get_console().items()):
            line = f"{v}\n"
            pretty_history += line
        msg = QtWidgets.QMessageBox()
        msg.setWindowTitle(f"ExperimentDB: {self.fileset.get_name()}")
        msg.setText(pretty_history)
        msg.exec_()

    def add_notes(self):
        if self.fileset is None:
            return self.console_print("Err: Must first load data", level="warning")

        # Add any notes to the fileset
        self.fileset.add_notes(self.notesPlainText.toPlainText())
        self.console_print("Notes added to fileset")
        self.autosave()

    def update_header(self):
        # Header should reflect opened data
        self.currSetNameLineEdit.setText(self.fileset.get_name())
        self.currDeviceLineEdit.setText(self.fileset.get_device())

        # Stacked widget should show the correct widget for the opened data
        new_page = self.stackedWidget.widget(self.devices[self.fileset.get_device()])
        self.stackedWidget.setCurrentWidget(new_page)

    def report_progress(self, progress: int):
        assert isinstance(progress, int)
        assert 0 <= progress <= 100
        self.progressBar.setValue(progress)

    def plot_manager(self):
        """
            This can last a long time and will therefore instantiate a QThread to leave the gui responsive.
        """
        # Grab the selected files for plotting
        fileset_time = datetime.datetime.now().strftime("%Y.%m.%d_%H.%M.%S")
        experiment_time = self.fileset.get_experiment_date().strftime("%Y.%m.%d_%H.%M.%S")
        selected_fileset = fs.Fileset(fileset_time)
        selected_fileset.set_experiment_date(experiment_time)

        for item in self.selectedFilesList.selectedItems():
            lbl = item.text()
            path = self.fileset.get_filepath(lbl)
            selected_fileset.add_filepath(path, lbl)
            colour = self.fileset.get_colour(lbl)
            selected_fileset.add_colour(colour, lbl)

        selected_fileset.set_device(self.fileset.get_device())
        selected_fileset.set_structure_type(self.fileset.get_structure_type())
        selected_fileset.set_name(self.fileset.get_name())

        # Recursively search for QWidget children with an alias to collect options and get their values
        options_dict = {}
        for option in self.stackedWidget.currentWidget().findChildren(QtWidgets.QWidget):
            alias = option.property("alias")
            if alias is not None:
                options_dict[alias] = get_qwidget_value(option)
        options_dict["presentation"] = get_qwidget_value(self.presentationCheckBox)

        # Instantiate proper device class and set the data
        current_device = self.fileset.get_device()
        experiment_cls = getattr(analysis.device, current_device)

        # # Grab the correct plotting function and pass all options to it
        plot_type = self.plotTypeCombo.currentText()
        self.console_print(f"Producing {current_device}-{plot_type} plot for {self.fileset.get_name()}")

        # Create a new thread for the device class to run in
        self.thread = QtCore.QThread()
        # gui FEATURE REQUEST: Get legend title from gui/fileset
        self.experiment_worker = experiment_cls(current_device, selected_fileset, plot_type, legend="Legend title",
                                                options=options_dict)
        self.experiment_worker.moveToThread(self.thread)

        # Connect signals and slots for the worker thread
        self.thread.started.connect(self.experiment_worker.run)
        self.experiment_worker.finished.connect(self.thread.quit)
        self.experiment_worker.finished.connect(self.experiment_worker.deleteLater)
        self.thread.finished.connect(self.thread.deleteLater)
        self.experiment_worker.progress.connect(self.report_progress)

        # Start the thread
        self.thread.start()

        # FIXME: Final resets
        # self.longRunningBtn.setEnabled(False)
        # self.thread.finished.connect(
        #     lambda: self.longRunningBtn.setEnabled(True)
        # )
        # self.thread.finished.connect(
        #     lambda: self.stepLabel.setText("Long-Running Step: 0")
        # )

    def toggle_lbic_profile(self):
        # Allow the profile position to be selected (LBIC specific)
        if self.lbicProfilesCheckBox.isChecked():
            self.lbicProfilesSpinBox.setEnabled(True)
        else:
            self.lbicProfilesSpinBox.setDisabled(True)

    def console_print(self, fstring, level="normal"):
        # Print a message to the gui console
        now = datetime.datetime.now()
        fstring_to_print = now.strftime("%d/%m/%Y %H.%M.%S: ") + fstring

        c = ConsoleColours()

        self.consoleTextEdit.setTextColor(c.get_colour(level))
        self.consoleTextEdit.append(fstring_to_print)
        self.consoleTextEdit.setTextColor(c.get_colour("normal"))

    def append_console_to_set(self):
        if self.fileset is None:
            return self.console_print("Err: Must first load data", level="warning")

        # Append console contents to the fileset
        console_text = self.consoleTextEdit.toPlainText()
        now = datetime.datetime.now()
        self.fileset.add_console(now.strftime("%d%m%Y_%H%M%S"), console_text)
        self.console_print("Added console contents to set")
        self.autosave()

    def clear_data(self):
        # Reset fields and properties related to data
        self.fileset = None
        self.fileset_location = None

        self.currSetNameLineEdit.clear()
        self.currDeviceLineEdit.clear()
        self.notesPlainText.clear()
        self.console_print("Cleared data from memory")

        self.stackedWidget.setCurrentWidget(self.stackedWidget.widget(0))
        self.selectedFilesList.clear()
        self.plotTypeCombo.clear()

    def clear_all(self):
        # Reset complete gui
        self.clear_data()
        self.consoleTextEdit.clear()
        self.console_print("Cleared memory")

    def show_about(self):
        """
            Shows a simple window with licence, authorship and build information
            # gui FEATURE REQUEST: Make it so it can contain the X-Lab Logo
        """
        # Grab the "about" info from about.txt
        with open("about.txt") as about_file:
            about_contents = about_file.read()

        # Show a basic about message
        msg = QtWidgets.QMessageBox(self.centralwidget)
        msg.setWindowTitle("About")
        msg.setText(about_contents)
        msg.exec_()

    def not_implemented(self):
        """
            Shows the user a message that the current feature is planned but not yet implemented.
        """
        self.console_print("Feature not implemented", level='warning')

    @staticmethod
    def quit():
        # Terminate the application
        sys.exit()


if __name__ == "__main__":
    # Initialise app, window and start execution
    app = QtWidgets.QApplication(sys.argv)
    window = UiMainWindow()
    app.exec_()
