# Main.py
import importlib
from PyQt5 import QtWidgets, uic, QtCore
import datetime
import json
import logging
import sys
import os
import fileset as fs
import utils
from utils.get_class_methods import get_class_methods
from utils.console_colours import ConsoleColours
from utils import constants

from gui.dialogs.generate_about_dialog import generate_about_dialog
from gui.clear.clear_data import clear_data
from gui.clear.clear_all import clear_all

from gui.data.load_data import open_data_file
from gui.data.save_data import save_data
from gui.data.create_data import create_data

from gui.dialogs.dialog_print import dialog_print

from gui.plot_manager import plot_manager

from functools import partial

# Read the JSON config file
if os.name == "nt":
    config_file = 'config_win.json'
else:
    config_file = 'config_linux.json'

with open(config_file) as f:
    config = json.load(f)

# Get the analysis package path
analysis_path = config['analysis_path']

# # Add the analysis package path to the system path and import it
# sys.path.insert(0, analysis_path)
# sys.path.append("../..")
import analysis.devices as devices


# Added a comment
class UiMainWindow(QtWidgets.QMainWindow):
    """
        gui for automated plotting of various types of data.
        MainWindow.ui is generated by QtDesigner version 6.4.1
    """
    def __init__(self):
        super(UiMainWindow, self).__init__()
        self.thread = None
        self.experiment_worker = None
        self.fileset = None
        self.fileset_location = None

        # Load the UI, Note that loadUI adds objects to 'self' using objectName
        self.dataWindow = None
        uic.loadUi("windows/MainWindow.ui", self)

        # Create/Get a logger with the desired settings
        self.logger = logging.getLogger(constants.LOG_NAME)
        self.consoleTextEdit.setFormatter(
            logging.Formatter(
                "%(asctime)s [%(levelname)8.8s] %(message)s",
                datefmt=f'{constants.DATETIME_FORMAT}: '
            )
        )
        self.logger.addHandler(self.consoleTextEdit)
        log_level = getattr(utils.logging, config["log_level"])
        self.logger.setLevel(log_level)

        self.plot_types = {}
        self.devices = {}

        # Get list of devices as defined manually in the.devices __init__.py file
        for entry in devices.__all__:
            # Find and load the widget for any given device and add it to the stackedWidget
            entry_ui_file = entry.lower() + ".ui"
            entry_widget = uic.loadUi(config["widgets_path"] + entry_ui_file)
            entry_index = self.stackedWidget.addWidget(entry_widget)
            self.devices[entry] = entry_index

            # Import the corresponding module and get the class methods to add to the plot_types combobox when needed
            module = importlib.import_module(f"{devices.workers.__name__}.{entry.lower()}")
            entry_cls = getattr(module, entry)
            self.plot_types[entry] = get_class_methods(entry_cls, ignore=["run"])

        # Reset stacked widget to empty page
        self.stackedWidget.setCurrentWidget(self.stackedWidget.widget(0))

        # Define menubar actions
        self.actionCreate_Set.triggered.connect(partial(create_data, window=self))
        self.actionSave_Set.triggered.connect(partial(save_data, window=self))
        self.actionLoad_Set.triggered.connect(partial(open_data_file, window=self))
        self.actionPreferences.triggered.connect(self.not_implemented)
        self.actionQuit.triggered.connect(self.quit)

        self.actionSave_format.triggered.connect(self.not_implemented)
        self.actionColour_scheme.triggered.connect(self.not_implemented)
        self.actionLine_width.triggered.connect(self.not_implemented)

        self.actionDocumentation.triggered.connect(self.not_implemented)
        self.actionAbout.triggered.connect(self.show_about)

        # Define gui button actions
        self.showDataBtn.clicked.connect(self.display_data)
        self.showHistoryBtn.clicked.connect(self.display_history)
        self.addNotesBtn.clicked.connect(self.add_notes)

        self.appendBtn.clicked.connect(self.append_console_to_set)
        self.clearBtn.clicked.connect(partial(clear_data, window=self))
        self.clearAllBtn.clicked.connect(partial(clear_all, window=self))
        self.quitBtn.clicked.connect(self.quit)

        # Define stackedWidget widget actions
        self.plotBtn.clicked.connect(partial(plot_manager, window=self, config=config))

        # Make sure the progress bar is cleared
        self.progressBar.setValue(0)

        # Show the app
        self.show()
        self.console_print("Program Started")

    def autosave(self):
        file_name = self.fileset_location
        if file_name is None:
            return self.console_print("Cannot autosave, no file location known. Open or create dataset first")

        with open(file_name, "w") as json_file:
            json.dump(self.fileset, json_file, cls=fs.FilesetJSONEncoder)
        json_file.close()
        return self.console_print(f"Saved data to {file_name}")

    def display_data(self):
        # Abort if no data was loaded
        if self.fileset is None:
            return self.console_print("Err: Must first load data", level="warning")

        # Pretty print the data in a simple dialog
        pretty_json = json.dumps(
            self.fileset,
            indent=4,
            separators=(',', ': '),
            cls=fs.FilesetJSONEncoder
        )
        dialog_print(window=self, title=f"ExperimentDB RAW: {self.fileset.get_name()}", contents=pretty_json)

    def display_history(self):
        if self.fileset is None:
            return self.console_print("Err: Must first load data", level="warning")

        # Prints only the console history to a simple dialog
        pretty_history = ""
        for k, v in sorted(self.fileset.get_console().items()):
            line = f"{v}\n"
            pretty_history += line

        dialog_print(window=self, title=f"ExperimentDB History: {self.fileset.get_name()}", contents=pretty_history)

    def add_notes(self):
        if self.fileset is None:
            return self.console_print("Err: Must first load data", level="warning")

        # Add any notes to the fileset
        self.fileset.add_notes(self.notesPlainText.toPlainText())
        self.console_print("Notes added to fileset")
        self.autosave()

    def update_header(self):
        # Header should reflect opened data
        self.currSetNameLineEdit.setText(self.fileset.get_name())
        self.currDeviceLineEdit.setText(self.fileset.get_device())

        # Stacked widget should show the correct widget for the opened data
        new_page = self.stackedWidget.widget(self.devices[self.fileset.get_device()])
        self.stackedWidget.setCurrentWidget(new_page)

    def report_progress(self, progress: int):
        assert isinstance(progress, int)
        assert 0 <= progress <= 100
        self.progressBar.setValue(progress)

    def save_to_file(self, plaintext: str):
        file_dialog = QtWidgets.QFileDialog.getSaveFileName(self, "Save File", "", "Text Files (*.txt);;All Files (*)")
        if file_dialog[0]:  # Check if a file was selected
            file_path = file_dialog[0]
            with open(file_path, 'w') as file:
                file.write(plaintext)

    def console_print(self, fstring, level="normal"):
        # Print a message to the gui console
        now = datetime.datetime.now()
        fstring_to_print = now.strftime(f"{constants.DATETIME_FORMAT}: ") + fstring

        c = ConsoleColours()

        self.consoleTextEdit.setTextColor(c.get_colour(level))
        self.consoleTextEdit.append(fstring_to_print)
        self.consoleTextEdit.setTextColor(c.get_colour("normal"))

    def append_console_to_set(self):
        if self.fileset is None:
            return self.console_print("Err: Must first load data", level="warning")

        # Append console contents to the fileset
        console_text = self.consoleTextEdit.toPlainText()
        now = datetime.datetime.now()
        self.fileset.add_console(now.strftime(constants.DATETIME_FORMAT), console_text)
        self.console_print("Added console contents to set")
        self.autosave()

    def show_about(self):
        """
            Shows a simple window with licence, authorship and build information
        """
        # Grab the "about" info from about.txt
        with open("../about.txt") as about_file:
            about_contents = about_file.read()

        about_dialog = generate_about_dialog(about_contents, self.centralWidget(), config)

        # Show the about dialog
        about_dialog.exec_()

    def reload_preferences(self):
        # Read the JSON config file
        with open(config_file) as f:
            config = json.load(f)
        self.console_print("Preferences loaded from config file")

    def not_implemented(self):
        """
            Shows the user a message that the current feature is planned but not yet implemented.
        """
        self.console_print("Feature not implemented", level='warning')

    # ESC now triggers a program exit
    def keyPressEvent(self, event) -> None:
        if event.key() == QtCore.Qt.Key.Key_Escape:
            self.quit()
        else:
            super(UiMainWindow, self).keyPressEvent(event)

    # CHECK: Program exit is not safe
    @staticmethod
    def quit():
        # Terminate the application
        sys.exit()


if __name__ == "__main__":
    # Initialise app, window and start execution
    app = QtWidgets.QApplication(sys.argv)
    window = UiMainWindow()
    app.exec_()
